
package com.spring.soap.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountDAO", targetNamespace = "http://cxf.soap.spring.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountDAO {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://cxf.soap.spring.com/", className = "com.spring.soap.cxf.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://cxf.soap.spring.com/", className = "com.spring.soap.cxf.DepositResponse")
    public String deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestCheckBook", targetNamespace = "http://cxf.soap.spring.com/", className = "com.spring.soap.cxf.RequestCheckBook")
    @ResponseWrapper(localName = "requestCheckBookResponse", targetNamespace = "http://cxf.soap.spring.com/", className = "com.spring.soap.cxf.RequestCheckBookResponse")
    public int requestCheckBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
